Repository oxsecurity/megalinter, pull requests merged in 2022-09, with the labels that each got.

#1818 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
Labels: dependencies, automerge

#1827 Run MegaLinter pre-commit hooks serially
  .pre-commit-hooks.yaml
  CHANGELOG.md
  mega-linter-runner/README.md
Labels: bug

#1824 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/javascript_standard.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/typescript_standard.md
  docs/mega-linter-runner.md
  docs/special-thanks.md
Labels: dependencies, automerge

#1831 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1834 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1837 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1839 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/bash_shellcheck.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_gitleaks.md
  docs/flavors/ci_light.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/security.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#1848 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/articles.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/kotlin_ktlint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/rst_rstcheck.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terraform_fmt.md
Labels: dependencies, automerge

#1858 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/latex_chktex.md
  docs/descriptors/lua_luacheck.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_dustilock.md
Labels: dependencies, automerge

#1864 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/bash_shellcheck.md
  docs/descriptors/html_djlint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/rust.md
  docs/descriptors/rust_clippy.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/yaml_yamllint.md
Labels: dependencies, automerge

#1870 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  .trivyignore
  CHANGELOG.md
  Dockerfile
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/html_htmlhint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_dustilock.md
  docs/descriptors/repository_secretlint.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/descriptors/terraform_terragrunt.md
  flavors/python/Dockerfile
  megalinter/descriptors/python.megalinter-descriptor.yml
Labels: dependencies, automerge

#1873 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terragrunt.md
Labels: dependencies, automerge

#1874 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1876 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  .trivyignore
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1878 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/scala_scalafix.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1881 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/python_black.md
Labels: dependencies, automerge

#1884 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1891 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/scala_scalafix.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_tflint.md
Labels: dependencies, automerge

#1894 [automation] Auto-update linters version, help and documentation
  .automation/build.py
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  .github/linters/.cspell.json
  .trivyignore
  .vscode/extensions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/bash_bash_exec.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1896 Document `-f` Argument to mega-linter-runner
  CHANGELOG.md
  mega-linter-runner/README.md
  megalinter/MegaLinter.py
  megalinter/utils.py
Labels: documentation

#1899 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/rust_clippy.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/mega-linter-runner.md
Labels: dependencies, automerge

#1902 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
Labels: dependencies, automerge

#1905 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
Labels: dependencies, automerge

#1908 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/json_jsonlint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_mypy.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_tflint.md
Labels: dependencies, automerge

#1912 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  .github/linters/.cspell.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/sql_sqlfluff.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge
