Repository oxsecurity/megalinter, pull requests merged in 2022-10, with the labels that each got.

#1914 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  .github/workflows/deploy-DEV.yml
  .trivyignore
  CHANGELOG.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/installation.md
Labels: dependencies, automerge

#1919 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/coffee_coffeelint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terragrunt.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#1928 Correct casing of `removeContainer` in mega-linter-runner
  CHANGELOG.md
  mega-linter-runner/lib/runner.js
Labels: bug

#1929 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/action_actionlint.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1571 Correct spelling of `containername` argument.
  .pre-commit-hooks.yaml
  mega-linter-runner/README.md
  mega-linter-runner/lib/options.js
  mega-linter-runner/lib/runner.js
Labels: bug, nostale

#1945 Add a more intuitive ´nostale´ label to stale bot exemptions
  .github/workflows/stale.yml
Labels: automation

#1952 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1954 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/action_actionlint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1957 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/scala_scalafix.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1963 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
Labels: dependencies, automerge

#1968 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/html_djlint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/puppet_puppet_lint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
Labels: dependencies, automerge

#1970 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1971 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1972 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/megalinter-users.json
  .github/linters/.cspell.json
  README.md
  docs/articles.md
  docs/descriptors/python_black.md
Labels: dependencies, automerge

#1981 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  .trivyignore
  CHANGELOG.md
  Dockerfile
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/arm_arm_ttk.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/puppet_puppet_lint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_git_diff.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terrascan.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  flavors/security/Dockerfile
  linters/repository_devskim/Dockerfile
  mega-linter-runner/.trivyignore
  megalinter/descriptors/repository.megalinter-descriptor.yml
Labels: dependencies, automerge

#1989 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#1984 Don't add literal double quote characters to filenames
  CHANGELOG.md
  mega-linter-runner/lib/runner.js
Labels: bug

#1991 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_gitleaks.md
Labels: dependencies, automerge

#2002 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/python_mypy.md
  docs/descriptors/python_pylint.md
  docs/descriptors/yaml_yamllint.md
Labels: dependencies, automerge

#2004 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubeconform.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_tflint.md
Labels: dependencies, automerge

#2014 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_kics.md
Labels: dependencies, automerge

#2016 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
Labels: dependencies, automerge

#2024 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_secretlint.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/sql_sqlfluff.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#2026 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/all_users.md
  docs/articles.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#2028 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/sql_sqlfluff.md
Labels: dependencies, automerge
