Repository oxsecurity/megalinter, pull requests merged in 2023-12, with the labels that each got.

#2402 Update dotnet linters to .NET 7
  .trivyignore
  Dockerfile
  docs/descriptors/csharp.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/repository_devskim.md
  docs/descriptors/sql_tsqllint.md
  docs/descriptors/vbdotnet.md
  flavors/dotnet/Dockerfile
  flavors/dotnetweb/Dockerfile
  flavors/formatters/Dockerfile
  flavors/security/Dockerfile
  linters/csharp_csharpier/Dockerfile
  linters/csharp_dotnet_format/Dockerfile
  linters/csharp_roslynator/Dockerfile
  linters/repository_devskim/Dockerfile
  linters/sql_tsqllint/Dockerfile
  linters/vbdotnet_dotnet_format/Dockerfile
  megalinter/descriptors/csharp.megalinter-descriptor.yml
  megalinter/descriptors/repository.megalinter-descriptor.yml
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
  megalinter/descriptors/sql.megalinter-descriptor.yml
  megalinter/descriptors/vbdotnet.megalinter-descriptor.yml
  megalinter/linters/DotNetToolLinter.py
  megalinter/linters/DotnetLinter.py
  megalinter/linters/RoslynatorLinter.py
Labels: nostale

#3172 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/repository_trivy_sbom.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3187 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3190 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/articles.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3199 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/lua_luacheck.md
  docs/descriptors/markdown_markdownlint.md
  docs/descriptors/php_phpcs.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_bandit.md
  docs/descriptors/python_isort.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/terraform_terragrunt.md
  docs/flavors/c_cpp.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/dotnetweb.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3204 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/spell_vale.md
  docs/flavors/c_cpp.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/dotnetweb.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/security.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3207 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/ruby_rubocop.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3214 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/python_isort.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/flavors/c_cpp.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/dotnetweb.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/security.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3215 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3216 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3210 tekton-lint is now published as @ibm/tekton-lint
  CHANGELOG.md
  Dockerfile
  flavors/c_cpp/Dockerfile
  flavors/documentation/Dockerfile
  flavors/dotnet/Dockerfile
  flavors/dotnetweb/Dockerfile
  flavors/go/Dockerfile
  flavors/java/Dockerfile
  flavors/javascript/Dockerfile
  flavors/php/Dockerfile
  flavors/python/Dockerfile
  flavors/ruby/Dockerfile
  flavors/rust/Dockerfile
  flavors/salesforce/Dockerfile
  flavors/swift/Dockerfile
  flavors/terraform/Dockerfile
  linters/tekton_tekton_lint/Dockerfile
  megalinter/descriptors/tekton.megalinter-descriptor.yml
Labels: dependencies

#3219 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/json_eslint_plugin_jsonc.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_isort.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/tekton_tekton_lint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3220 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/json_eslint_plugin_jsonc.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3222 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_syft.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3223 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/css_scss_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_devskim.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/terraform_terragrunt.md
  docs/descriptors/xml_xmllint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3229 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_syft.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terrascan.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3231 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_syft.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3232 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_roslynator.md
  docs/descriptors/php.md
  docs/descriptors/php_phpcs.md
  docs/descriptors/php_phplint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/php_psalm.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/used-by-stats.md
  megalinter/descriptors/csharp.megalinter-descriptor.yml
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3238 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/repository_trivy_sbom.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3245 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/json_eslint_plugin_jsonc.md
  docs/descriptors/kotlin_ktlint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_mypy.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_kics.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3246 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3247 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3249 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3251 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3233 mega-linter-runner: Improve check if running as script or module
  CHANGELOG.md
  mega-linter-runner/lib/index.js
Labels: javascript

#3193 Use docker/metadata-action for deploy-DEV.yml
  .github/workflows/deploy-DEV.yml
  CHANGELOG.md
  mega-linter-runner/test/megalinter-cli.test.js
  mega-linter-runner/test/megalinter-module.test.js
Labels: infrastructure

#3252 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/dockerfile.md
  docs/descriptors/dockerfile_hadolint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_isort.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_secretlint.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/rust_clippy.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
  docs/mega-linter-vs-super-linter.md
  docs/reporters.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3257 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terrascan.md
  docs/descriptors/terraform_tflint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3259 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge
