Repository oxsecurity/megalinter, pull requests merged in 2023-04, with the labels that each got.

#2496 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/php_psalm.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/flavors/ci_light.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  flavors/cupcake/Dockerfile
  flavors/documentation/Dockerfile
  flavors/dotnet/Dockerfile
  flavors/go/Dockerfile
  flavors/java/Dockerfile
  flavors/javascript/Dockerfile
  flavors/php/Dockerfile
  flavors/python/Dockerfile
  flavors/ruby/Dockerfile
  flavors/rust/Dockerfile
  flavors/salesforce/Dockerfile
  flavors/swift/Dockerfile
  flavors/terraform/Dockerfile
  linters/markdown_markdown_link_check/Dockerfile
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2508 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/rst_rstfmt.md
  docs/descriptors/scala.md
  docs/descriptors/scala_scalafix.md
  docs/descriptors/spell_misspell.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2511 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/badge.md
  docs/configuration.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/installation.md
  docs/plugins.md
  docs/special-thanks.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2513 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .github/linters/.cspell.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
  megalinter/reporters/AzureCommentReporter.py
  megalinter/utils_reporter.py
Labels: dependencies, automerge

#2518 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2520 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2522 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/python_pylint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2455 Ensure ESLint actually runs in project mode (#1572)
  CHANGELOG.md
  megalinter/linters/EslintLinter.py
Labels: bug

#2527 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/html_djlint.md
  docs/descriptors/puppet_puppet_lint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/snakemake_snakefmt.md
  docs/descriptors/sql_sqlfluff.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2551 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2553 Add support for idea plugins auto-install
  .github/linters/.cspell.json
  CHANGELOG.md
  docs/reporters/ConfigReporter.md
  megalinter/descriptors/cloudformation.megalinter-descriptor.yml
  megalinter/descriptors/coffee.megalinter-descriptor.yml
  megalinter/descriptors/css.megalinter-descriptor.yml
  megalinter/descriptors/dart.megalinter-descriptor.yml
  megalinter/descriptors/java.megalinter-descriptor.yml
  megalinter/descriptors/javascript.megalinter-descriptor.yml
  megalinter/descriptors/json.megalinter-descriptor.yml
  megalinter/descriptors/jsx.megalinter-descriptor.yml
  megalinter/descriptors/php.megalinter-descriptor.yml
  megalinter/descriptors/protobuf.megalinter-descriptor.yml
  megalinter/descriptors/python.megalinter-descriptor.yml
  megalinter/descriptors/salesforce.megalinter-descriptor.yml
  megalinter/descriptors/snakemake.megalinter-descriptor.yml
  megalinter/descriptors/spell.megalinter-descriptor.yml
  megalinter/descriptors/swift.megalinter-descriptor.yml
  megalinter/descriptors/terraform.megalinter-descriptor.yml
  megalinter/descriptors/tsx.megalinter-descriptor.yml
  megalinter/descriptors/typescript.megalinter-descriptor.yml
  megalinter/descriptors/yaml.megalinter-descriptor.yml
  megalinter/reporters/ConfigReporter.py
Labels: enhancement

#2542 Fix `/build` slash command to checkout the correct PR branch
  .github/workflows/build-command.yml
  .github/workflows/slash-command-dispatch.yml
  CHANGELOG.md
Labels: github_actions, automation

#2552 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2558 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/html_djlint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/sql_sqlfluff.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/used-by-stats.md
  flavors/cupcake/Dockerfile
  flavors/security/Dockerfile
  flavors/terraform/Dockerfile
  linters/terraform_terrascan/Dockerfile
  mega-linter-runner/README.md
  megalinter/descriptors/terraform.megalinter-descriptor.yml
Labels: dependencies, automerge

#2563 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terrascan.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2567 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2569 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2571 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/arm_arm_ttk.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2572 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#1982 Allow use of configuration files with v8r
  megalinter/descriptors/yaml.megalinter-descriptor.yml
Labels: nostale

#2577 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terragrunt.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2583 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/kotlin_ktlint.md
  docs/descriptors/puppet_puppet_lint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/rust_clippy.md
  docs/descriptors/sql_sqlfluff.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/descriptors/xml_xmllint.md
  docs/descriptors/yaml_yamllint.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2585 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/protobuf_protolint.md
  docs/used-by-stats.md
  entrypoint.sh
  megalinter/setup.py
Labels: dependencies, automerge

#2588 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2589 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/css_stylelint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2590 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/javascript_prettier.md
  docs/descriptors/json_prettier.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/typescript_prettier.md
  docs/descriptors/yaml_prettier.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2593 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/articles.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
  flavors/cupcake/Dockerfile
  flavors/security/Dockerfile
  flavors/terraform/Dockerfile
  linters/terraform_tflint/Dockerfile
  megalinter/descriptors/terraform.megalinter-descriptor.yml
Labels: dependencies, automerge

#2599 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/copypaste_jscpd.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/json_jsonlint.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2600 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2603 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  docs/all_linters.md
  docs/configuration.md
  docs/descriptors/arm_arm_ttk.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/markdown_markdownlint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/rst_rstcheck.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_checkov.md
  docs/licenses/htmlhint.md
  docs/licenses/php.md
  docs/reporters/EmailReporter.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge
