Repository oxsecurity/megalinter, pull requests merged in 2023-02, with the labels that each got.

#2316 Remove unneeded go install requirement for shfmt
  flavors/ci_light/Dockerfile
  megalinter/descriptors/bash.megalinter-descriptor.yml
Labels: performance

#2313 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2323 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/bash_bash_exec.md
  docs/descriptors/bash_shfmt.md
  docs/descriptors/dart_dartanalyzer.md
  docs/descriptors/python_isort.md
  docs/descriptors/python_mypy.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_git_diff.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/xml_xmllint.md
  docs/index.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2326 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/javascript_prettier.md
  docs/descriptors/json_prettier.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/typescript_prettier.md
  docs/descriptors/yaml_prettier.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2334 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/openapi_spectral.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/terraform_checkov.md
  docs/flavors/ci_light.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/security.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2336 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/copypaste_jscpd.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_secretlint.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/flavors/ci_light.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2347 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/arm.md
  docs/descriptors/arm_arm_ttk.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/openapi_spectral.md
  docs/descriptors/powershell.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terrascan.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2350 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/php.md
  docs/descriptors/php_phpcs.md
  docs/descriptors/php_phplint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/php_psalm.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2352 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/editorconfig_editorconfig_checker.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/security.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2355 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
  docs/flavors/cupcake.md
  docs/flavors/python.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2359 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/descriptors/terraform_tflint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2364 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/csharp_dotnet_format.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_git_diff.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/descriptors/vbdotnet_dotnet_format.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2366 Added rubocop-rake RubyGem for linting Rake files with RuboCop
  CHANGELOG.md
  Dockerfile
  docs/descriptors/ruby_rubocop.md
  flavors/cupcake/Dockerfile
  flavors/ruby/Dockerfile
  linters/ruby_rubocop/Dockerfile
  megalinter/descriptors/ruby.megalinter-descriptor.yml
Labels: enhancement

#2365 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_mypy.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2370 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2372 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/php_psalm.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2373 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2374 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/action.md
  docs/descriptors/action_actionlint.md
  docs/descriptors/bash_shellcheck.md
  docs/descriptors/bash_shfmt.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/dockerfile_hadolint.md
  docs/descriptors/editorconfig_editorconfig_checker.md
  docs/descriptors/go.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/go_revive.md
  docs/descriptors/html_djlint.md
  docs/descriptors/latex_chktex.md
  docs/descriptors/makefile_checkmake.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/php_psalm.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_dustilock.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/descriptors/terraform_terrascan.md
  docs/descriptors/terraform_tflint.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
  megalinter/descriptors/action.megalinter-descriptor.yml
  megalinter/descriptors/repository.megalinter-descriptor.yml
  megalinter/tests/test_megalinter/config_test.py
Labels: dependencies, automerge

#2385 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .github/linters/.checkov.yml
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/configuration.md
  docs/descriptors/php_phpcs.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/php_psalm.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2393 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/php_psalm.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2394 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/java_checkstyle.md
  docs/used-by-stats.md
  megalinter/tests/test_megalinter/config_test.py
Labels: dependencies, automerge

#2381 Fixup changes/no changes exit codes for build-command
  .github/workflows/build-command.yml
  .github/workflows/deploy-DEV-linters.yml
  .github/workflows/deploy-DEV.yml
  .github/workflows/test-mega-linter-runner.yml
  CHANGELOG.md
Labels: enhancement

#2395 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2398 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge
