Repository oxsecurity/megalinter, pull requests merged in 2023-11, with the labels that each got.

#3056 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3066 Set schedule earlier for auto-update-linters.yml, allow manual runs
  .github/workflows/auto-update-linters.yml
Labels: github_actions

#3063 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3078 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/json_npm_package_json_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3080 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3084 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/repository_trivy_sbom.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3085 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3093 Modernize dependabot.yml in correct directories
  .github/dependabot.yml
Labels: dependencies, infrastructure

#3109 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/csharp_dotnet_format.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/python.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_terragrunt.md
  docs/descriptors/vbdotnet_dotnet_format.md
  docs/flavors/cupcake.md
  docs/flavors/python.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3117 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/arm.md
  docs/descriptors/arm_arm_ttk.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/kubernetes_kubeconform.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/powershell.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/r_lintr.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/rust_clippy.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/descriptors/terraform_tflint.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3131 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/articles.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/install-gitlab.md
  docs/mega-linter-vs-super-linter.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3132 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/xml_xmllint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3134 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3136 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3144 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3145 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3148 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/puppet_puppet_lint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3153 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_psalm.md
  docs/descriptors/puppet_puppet_lint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3154 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/python_mypy.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3156 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3158 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3159 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_table_formatter.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3161 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/java.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/java_pmd.md
  docs/descriptors/kotlin.md
  docs/descriptors/kotlin_ktlint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/scala.md
  docs/descriptors/scala_scalafix.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3162 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3163 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_secretlint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3165 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3167 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3168 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3169 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_secretlint.md
  docs/used-by-stats.md
Labels: dependencies, automerge
