Repository oxsecurity/megalinter, pull requests merged in 2023-01, with the labels that each got.

#2207 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/python_black.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2208 [automation] Auto-update linters version, help and documentation
  .automation/build.py
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_secretlint.md
  docs/descriptors/ruby_rubocop.md
  docs/installation.md
  docs/used-by-stats.md
  mega-linter-runner/generators/mega-linter/templates/.drone.yml
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2211 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2214 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/configuration.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kotlin_ktlint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_secretlint.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2218 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/html_djlint.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2221 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2223 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/all_users.md
  docs/descriptors/json_eslint_plugin_jsonc.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2224 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/csharp_dotnet_format.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_devskim.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/sql_tsqllint.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/vbdotnet.md
  docs/descriptors/vbdotnet_dotnet_format.md
  docs/flavors/dotnet.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2226 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/markdown_markdownlint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2232 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_dotnet_format.md
  docs/descriptors/perl_perlcritic.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_tflint.md
  docs/descriptors/vbdotnet_dotnet_format.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2238 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
  megalinter/config.py
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
  megalinter/tests/test_megalinter/config_test.py
Labels: dependencies, automerge

#2245 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_dotnet_format.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/vbdotnet_dotnet_format.md
  docs/descriptors/xml_xmllint.md
  docs/descriptors/yaml_yamllint.md
  docs/used-by-stats.md
  megalinter/linters/PowershellLinter.py
Labels: dependencies, automerge

#2251 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_devskim.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2255 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2259 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/terraform_checkov.md
  docs/installation.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2260 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .automation/generated/megalinter-users.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/javascript_prettier.md
  docs/descriptors/json_prettier.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/typescript_prettier.md
  docs/descriptors/yaml_prettier.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2261 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/python_black.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2268 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/python_black.md
  docs/used-by-stats.md
  megalinter/utils.py
Labels: dependencies, automerge

#2274 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_git_diff.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2276 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2278 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/action_actionlint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/sql_tsqllint.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2275 Pass extra args for friendlier CSpell UX (#2271)
  .github/linters/.cspell.json
  CHANGELOG.md
  megalinter/linters/CSpellLinter.py
Labels: bug

#2283 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2285 Tag some automatically updated files as generated files
  .gitattributes
Labels: automation

#2290 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/kotlin_ktlint.md
  docs/descriptors/php_psalm.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/xml_xmllint.md
  docs/licenses/cpplint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2292 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2293 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/go_revive.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_syft.md
  docs/descriptors/rst_rstfmt.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/rust_clippy.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2296 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/css_scss_lint.md
  docs/descriptors/json_v8r.md
  docs/descriptors/python_black.md
  docs/descriptors/python_isort.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2297 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/python_black.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2280 Only Run npm-package-json-lint When `package.json` is Present
  CHANGELOG.md
  megalinter/descriptors/json.megalinter-descriptor.yml
  megalinter/flavor_factory.py
Labels: bug

#2304 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/json_npm_package_json_lint.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_syft.md
  docs/used-by-stats.md
  megalinter/reporters/AzureCommentReporter.py
Labels: dependencies, automerge

#2305 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/terraform_checkov.md
  docs/index.md
  docs/used-by-stats.md
Labels: dependencies, automerge
