Repository oxsecurity/megalinter, pull requests merged in 2023-10, with the labels that each got.

#2987 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2988 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2654 Only check for `@generated`-like markers in file header
  .cspell.json
  CHANGELOG.md
  megalinter/utils.py
Labels: nostale, performance

#3010 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3013 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3018 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_mypy.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3020 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3021 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3023 Set flavors-stats.json as a generated file in .gitattributes
  .gitattributes
  .trivyignore
  CHANGELOG.md
Labels: automation

#3022 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_devskim.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3027 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3028 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/json_eslint_plugin_jsonc.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3031 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3034 Update and fix our ChatOps automations to only run on pull request comments
  .github/workflows/build-command.yml
  .github/workflows/help-command.yml
  .github/workflows/slash-command-dispatch.yml
  CHANGELOG.md
Labels: github_actions, automation, infrastructure

#3035 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pylint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3037 Add failure message in ChatOps build-command and Slash dispatcher
  .github/workflows/build-command.yml
  .github/workflows/slash-command-dispatch.yml
  CHANGELOG.md
Labels: github_actions, automation

#3036 Use App::cpm to install perlcritic faster, and clean `.perl-cpm` cache
  CHANGELOG.md
  Dockerfile
  linters/perl_perlcritic/Dockerfile
  megalinter/descriptors/perl.megalinter-descriptor.yml
Labels: dependencies, docker, performance

#3040 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/json_v8r.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/perl_perlcritic.md
  docs/descriptors/python_black.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3042 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .python-version
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_dotnet_format.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/vbdotnet_dotnet_format.md
  docs/used-by-stats.md
  megalinter/descriptors/python.megalinter-descriptor.yml
Labels: dependencies, automerge

#3043 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/flavors/cupcake.md
  docs/flavors/python.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3045 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/sql_sqlfluff.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3048 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/repository_trivy_sbom.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3051 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3055 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
Labels: dependencies, automerge
