Repository oxsecurity/megalinter, pull requests merged in 2023-05, with the labels that each got.

#2606 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/copypaste_jscpd.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2610 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/configuration.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/copypaste_jscpd.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/json_eslint_plugin_jsonc.md
  docs/descriptors/json_v8r.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/php_psalm.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_mypy.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/sql_sqlfluff.md
  docs/descriptors/swift_swiftlint.md
  docs/descriptors/terraform_checkov.md
  docs/descriptors/terraform_kics.md
  docs/descriptors/terraform_terragrunt.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2624 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kotlin_ktlint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_checkov.md
Labels: dependencies, automerge

#2625 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2626 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/spell_vale.md
  docs/descriptors/swift_swiftlint.md
  docs/descriptors/terraform_checkov.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2628 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2531 added kubescape as a linter to megalinter/descriptors/kubernetes.meg…
  .automation/generated/linter-links-previews.json
  .automation/test/kubernetes_kubescape/bad/.helmignore
  .automation/test/kubernetes_kubescape/bad/Chart.yaml
  .automation/test/kubernetes_kubescape/bad/templates/_helpers.tpl
  .automation/test/kubernetes_kubescape/bad/templates/deployment.yaml
  .automation/test/kubernetes_kubescape/bad/templates/service.yaml
  .automation/test/kubernetes_kubescape/bad/values.yaml
  .automation/test/kubernetes_kubescape/good/.helmignore
  .automation/test/kubernetes_kubescape/good/Chart.yaml
  .automation/test/kubernetes_kubescape/good/templates/NOTES.txt
  .automation/test/kubernetes_kubescape/good/templates/_helpers.tpl
  .automation/test/kubernetes_kubescape/good/templates/deployment.yaml
  .automation/test/kubernetes_kubescape/good/templates/service.yaml
  .automation/test/kubernetes_kubescape/good/values.yaml
  .automation/test/terraform/bad/terraform_bad_1.tf
  .automation/test/terraform/bad/terraform_bad_2.tf
  .cspell.json
  .github/workflows/deploy-BETA-linters.yml
  .github/workflows/deploy-DEV-linters.yml
  .github/workflows/deploy-RELEASE-linters.yml
  Dockerfile
  docs/standalone-linters.md
  flavors/cupcake/Dockerfile
  flavors/cupcake/flavor.json
  flavors/documentation/Dockerfile
  flavors/documentation/flavor.json
  flavors/dotnet/Dockerfile
  flavors/dotnet/flavor.json
  flavors/go/Dockerfile
  flavors/go/flavor.json
  flavors/java/Dockerfile
  flavors/java/flavor.json
  flavors/javascript/Dockerfile
  flavors/javascript/flavor.json
  flavors/php/Dockerfile
  flavors/php/flavor.json
  flavors/python/Dockerfile
  flavors/python/flavor.json
  flavors/ruby/Dockerfile
  flavors/ruby/flavor.json
  flavors/rust/Dockerfile
  flavors/rust/flavor.json
  flavors/salesforce/Dockerfile
  flavors/salesforce/flavor.json
  flavors/security/Dockerfile
  flavors/security/flavor.json
  flavors/swift/Dockerfile
  flavors/swift/flavor.json
  flavors/terraform/Dockerfile
  flavors/terraform/flavor.json
  linters/kubernetes_kubescape/Dockerfile
  megalinter/descriptors/all_flavors.json
  megalinter/descriptors/kubernetes.megalinter-descriptor.yml
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
  megalinter/tests/test_megalinter/linters/kubernetes_kubescape_test.py
  megalinter/utils.py
Labels: nostale

#2640 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  Dockerfile
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php.md
  docs/descriptors/php_phpcs.md
  docs/descriptors/php_phplint.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/php_psalm.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
  flavors/cupcake/Dockerfile
  flavors/php/Dockerfile
  linters/php_phplint/Dockerfile
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2645 🐛 fix(sarif): update schema to pass validator
  .automation/test/sarif_reports/REPOSITORY_GITLEAKS.sarif
  megalinter/constants.py
  megalinter/server.py
Labels: bug

#2651 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/clojure.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/clojure_cljstyle.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/dart.md
  docs/descriptors/dart_dartanalyzer.md
  docs/descriptors/go_revive.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
  flavors/cupcake/Dockerfile
  flavors/documentation/Dockerfile
  flavors/dotnet/Dockerfile
  flavors/go/Dockerfile
  flavors/java/Dockerfile
  flavors/javascript/Dockerfile
  flavors/php/Dockerfile
  flavors/python/Dockerfile
  flavors/ruby/Dockerfile
  flavors/rust/Dockerfile
  flavors/salesforce/Dockerfile
  flavors/security/Dockerfile
  flavors/swift/Dockerfile
  flavors/terraform/Dockerfile
  linters/kubernetes_kubescape/Dockerfile
  megalinter/descriptors/kubernetes.megalinter-descriptor.yml
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2658 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2661 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdownlint.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#2663 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/configuration.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2671 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/javascript_eslint.md
  docs/descriptors/jsx_eslint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/tsx_eslint.md
  docs/descriptors/typescript_eslint.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2674 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2677 Decouple updating docker pull stats from building docs
  .automation/build.py
  CHANGELOG.md
  entrypoint.sh
Labels: documentation, automation, python, infrastructure

#2675 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2676 Review MegaLinter's own cspell word list for outdated exclusions
  .cspell.json
  .mega-linter.yml
  CHANGELOG.md
Labels: infrastructure

#2678 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2680 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/yaml_yamllint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2682 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_psalm.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2684 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/openapi_spectral.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2686 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/sql_sqlfluff.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#2696 [automation] Auto-update linters version, help and documentation + fix tflint secured env
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_tflint.md
  docs/used-by-stats.md
  megalinter/descriptors/terraform.megalinter-descriptor.yml
  megalinter/linters/TfLintLinter.py
Labels: dependencies, automerge

#2704 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/html_djlint.md
  docs/descriptors/javascript_standard.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/typescript_standard.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2705 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#2708 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .cspell.json
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/terraform_tflint.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/security.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  flavors/cupcake/Dockerfile
  flavors/documentation/Dockerfile
  flavors/dotnet/Dockerfile
  flavors/go/Dockerfile
  flavors/java/Dockerfile
  flavors/javascript/Dockerfile
  flavors/php/Dockerfile
  flavors/python/Dockerfile
  flavors/ruby/Dockerfile
  flavors/rust/Dockerfile
  flavors/salesforce/Dockerfile
  flavors/security/Dockerfile
  flavors/swift/Dockerfile
  flavors/terraform/Dockerfile
  linters/ansible_ansible_lint/Dockerfile
  mega-linter-runner/README.md
  megalinter/descriptors/ansible.megalinter-descriptor.yml
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
  megalinter/descriptors/terraform.megalinter-descriptor.yml
Labels: dependencies, automerge

#2709 [automation] Auto-update linters version, help and documentation
  .automation/generated/flavors-stats.json
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge
