Repository oxsecurity/megalinter, pull requests merged in 2024-06, with the labels that each got.

#3593 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3600 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/articles.md
  docs/descriptors/csharp_dotnet_format.md
  docs/descriptors/csharp_roslynator.md
  docs/descriptors/javascript_prettier.md
  docs/descriptors/json_prettier.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/typescript_prettier.md
  docs/descriptors/vbdotnet_dotnet_format.md
  docs/descriptors/yaml_prettier.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3606 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/bicep_bicep_linter.md
  docs/descriptors/javascript_prettier.md
  docs/descriptors/json_prettier.md
  docs/descriptors/json_v8r.md
  docs/descriptors/kotlin_ktlint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/repository_trivy_sbom.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/swift_swiftlint.md
  docs/descriptors/typescript_prettier.md
  docs/descriptors/yaml_prettier.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
  mega-linter-runner/.trivyignore
Labels: dependencies, automerge

#3620 enhancement: Powershell Error Table Format Improvements
  CHANGELOG.md
  megalinter/linters/PowershellLinter.py
Labels: enhancement, python

#3621 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
  megalinter/linters/PowershellLinter.py
Labels: dependencies, automerge

#3622 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/ansible_ansible_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/flavors/c_cpp.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/dotnetweb.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/security.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3617 Handle renovate version comments in build script
  .automation/build.py
  CHANGELOG.md
Labels: python, infrastructure

#3624 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3626 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_php_cs_fixer.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3638 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/descriptors/editorconfig_editorconfig_checker.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/java_pmd.md
  docs/descriptors/kotlin_detekt.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/powershell_powershell.md
  docs/descriptors/powershell_powershell_formatter.md
  docs/descriptors/rst_rst_lint.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_tflint.md
  docs/used-by-stats.md
  flavors/cupcake/Dockerfile
  flavors/python/Dockerfile
  linters/rst_rst_lint/Dockerfile
Labels: dependencies, automerge

#3646 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/java_pmd.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3648 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/markdown_markdown_table_formatter.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/repository_trivy_sbom.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/yaml_yamllint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3651 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/javascript_prettier.md
  docs/descriptors/json_prettier.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/typescript_prettier.md
  docs/descriptors/yaml_prettier.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3652 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_kics.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3653 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/python_bandit.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3654 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/rust_clippy.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
  megalinter/tests/test_megalinter/config_test.py
Labels: dependencies, automerge

#3659 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/repository_grype.md
  docs/descriptors/repository_syft.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/repository_trivy_sbom.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3660 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3661 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_php_cs_fixer.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3662 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/json_npm_package_json_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_flake8.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3663 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3666 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_php_cs_fixer.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
  megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
Labels: dependencies, automerge

#3682 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .github/FUNDING.yml
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/bash_bash_exec.md
  docs/descriptors/c_clang_format.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/cpp_clang_format.md
  docs/descriptors/kubernetes_helm.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_devskim.md
  docs/descriptors/repository_git_diff.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/xml.md
  docs/descriptors/xml_xmllint.md
  docs/flavors/cupcake.md
  docs/flavors/php.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
  megalinter/descriptors/repository.megalinter-descriptor.yml
Labels: dependencies, automerge

#3685 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3686 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3690 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3692 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3703 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/python_mypy.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
  flavors/dotnet/Dockerfile
  flavors/dotnetweb/Dockerfile
  flavors/formatters/Dockerfile
  flavors/security/Dockerfile
Labels: dependencies, automerge

#3707 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/java_pmd.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_pylint.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3717 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/action_actionlint.md
  docs/descriptors/bash_shellcheck.md
  docs/descriptors/dockerfile_hadolint.md
  docs/descriptors/editorconfig_editorconfig_checker.md
  docs/descriptors/go_revive.md
  docs/descriptors/kubernetes_kubeconform.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_dustilock.md
  docs/descriptors/repository_gitleaks.md
  docs/descriptors/repository_kics.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/descriptors/terraform_terrascan.md
  docs/descriptors/terraform_tflint.md
  docs/used-by-stats.md
Labels: dependencies, automerge
