Repository oxsecurity/megalinter, pull requests merged in 2024-08, with the labels that each got.

#3828 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubeconform.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_php_cs_fixer.md
  docs/descriptors/python_mypy.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_grype.md
  docs/descriptors/repository_trivy.md
  docs/descriptors/repository_trivy_sbom.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_vale.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3832 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/articles.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_black.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_semgrep.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3837 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/json_v8r.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/protobuf_protolint.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3839 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .cspell.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_flake8.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3843 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3851 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/articles.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/json_jsonlint.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_php_cs_fixer.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/python_pylint.md
  docs/descriptors/python_pyright.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_grype.md
  docs/descriptors/repository_syft.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
  docs/descriptors/swift_swiftlint.md
  docs/used-by-stats.md
  megalinter/descriptors/swift.megalinter-descriptor.yml
Labels: dependencies, automerge

#3860 Port Beta workflows to use docker/metadata-action
  .github/workflows/deploy-BETA-flavors.yml
  .github/workflows/deploy-BETA-linters.yml
  .github/workflows/deploy-BETA.yml
  .github/workflows/deploy-DEV-linters.yml
  .github/workflows/deploy-DEV.yml
  CHANGELOG.md
Labels: infrastructure

#3866 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_grype.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3867 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
  flavors/c_cpp/Dockerfile
  flavors/ci_light/Dockerfile
  flavors/cupcake/Dockerfile
  flavors/documentation/Dockerfile
  flavors/dotnet/Dockerfile
  flavors/dotnetweb/Dockerfile
  flavors/go/Dockerfile
  flavors/java/Dockerfile
  flavors/javascript/Dockerfile
  flavors/php/Dockerfile
  flavors/python/Dockerfile
  flavors/ruby/Dockerfile
  flavors/rust/Dockerfile
  flavors/salesforce/Dockerfile
  flavors/security/Dockerfile
  flavors/swift/Dockerfile
  flavors/terraform/Dockerfile
  linters/repository_grype/Dockerfile
  megalinter/descriptors/repository.megalinter-descriptor.yml
Labels: dependencies, automerge

#3868 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_grype.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/flavors/c_cpp.md
  docs/flavors/ci_light.md
  docs/flavors/cupcake.md
  docs/flavors/documentation.md
  docs/flavors/dotnet.md
  docs/flavors/dotnetweb.md
  docs/flavors/go.md
  docs/flavors/java.md
  docs/flavors/javascript.md
  docs/flavors/php.md
  docs/flavors/python.md
  docs/flavors/ruby.md
  docs/flavors/rust.md
  docs/flavors/salesforce.md
  docs/flavors/security.md
  docs/flavors/swift.md
  docs/flavors/terraform.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3869 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3873 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/csharp_dotnet_format.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/go.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/go_revive.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/repository_trufflehog.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/vbdotnet_dotnet_format.md
  docs/flavors/cupcake.md
  docs/flavors/go.md
  docs/index.md
  docs/supported-linters.md
  docs/used-by-stats.md
  mega-linter-runner/README.md
Labels: dependencies, automerge

#3875 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_ruff.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3540 New API Reporter for Http (ex: Grafana)
  .cspell.json
  .github/workflows/mega-linter.yml
  .vscode/launch.json
  CHANGELOG.md
  README.md
  docs/assets/images/grafana-config-1.jpg
  docs/assets/images/grafana-config-10.jpg
  docs/assets/images/grafana-config-11.jpg
  docs/assets/images/grafana-config-12.jpg
  docs/assets/images/grafana-config-13.jpg
  docs/assets/images/grafana-config-13bis.jpg
  docs/assets/images/grafana-config-2.jpg
  docs/assets/images/grafana-config-3.jpg
  docs/assets/images/grafana-config-4.jpg
  docs/assets/images/grafana-config-5.jpg
  docs/assets/images/grafana-config-6.jpg
  docs/assets/images/grafana-config-7.jpg
  docs/assets/images/grafana-config-8.jpg
  docs/assets/images/grafana-config-9.jpg
  docs/config-variables-security.md
  docs/grafana/DASH - 00_MegaLinter Home.json
  docs/grafana/DASH - ML Errors & Elapse.json
  docs/reporters/ApiReporter.md
  mega-linter-runner/generators/mega-linter/templates/mega-linter.yml
  megalinter/config.py
  megalinter/reporters/ApiReporter.py
  megalinter/tests/test_megalinter/config_test.py
  megalinter/tests/test_megalinter/mega_linter_3_sarif_test.py
  megalinter/utils.py
  megalinter/utilstest.py
  mkdocs.yml
Labels: nostale

#3878 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/config-variables-security.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/spell_cspell.md
  docs/reporters.md
  docs/used-by-stats.md
  megalinter/tests/test_megalinter/mega_linter_3_sarif_test.py
Labels: dependencies, automerge

#3882 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  Dockerfile
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_tflint.md
  docs/used-by-stats.md
  flavors/salesforce/Dockerfile
  linters/salesforce_lightning_flow_scanner/Dockerfile
  linters/salesforce_sfdx_scanner_apex/Dockerfile
  linters/salesforce_sfdx_scanner_aura/Dockerfile
  linters/salesforce_sfdx_scanner_lwc/Dockerfile
Labels: dependencies, automerge

#3886 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3889 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
  mkdocs.yml
Labels: dependencies, automerge

#3901 [automation] Auto-update linters version, help and documentation
  .automation/build.py
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/articles.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/index.md
  docs/reporters/ApiReporter.md
  docs/used-by-stats.md
  mkdocs.yml
Labels: dependencies, automerge

#3903 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .github/workflows/deploy-DEV.yml
  README.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/index.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3905 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3909 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/json_v8r.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3912 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/json_v8r.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3923 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  .trivyignore
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
  mega-linter-runner/.trivyignore
Labels: dependencies, automerge

#3924 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/go_golangci_lint.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3925 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/csharp_csharpier.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3927 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_mypy.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/swift_swiftlint.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3930 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3931 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/json_v8r.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/yaml_v8r.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3934 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_php_cs_fixer.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3939 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_phpstan.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
  renovate.json5
Labels: dependencies, automerge

#3941 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/css_stylelint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/php_php_cs_fixer.md
  docs/descriptors/python_pyright.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/descriptors/terraform_terraform_fmt.md
  docs/descriptors/terraform_terragrunt.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3946 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/config-precommands.md
  docs/descriptors/clojure_clj_kondo.md
  docs/descriptors/cloudformation_cfn_lint.md
  docs/descriptors/groovy_npm_groovy_lint.md
  docs/descriptors/html_djlint.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/python_ruff.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3949 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  docs/all_linters.md
  docs/descriptors/java_checkstyle.md
  docs/descriptors/java_pmd.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/repository_checkov.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge

#3952 [automation] Auto-update linters version, help and documentation
  .automation/generated/linter-helps.json
  .automation/generated/linter-versions.json
  CHANGELOG.md
  README.md
  docs/all_linters.md
  docs/descriptors/kubernetes_kubescape.md
  docs/descriptors/markdown_markdown_link_check.md
  docs/descriptors/php_php_cs_fixer.md
  docs/descriptors/ruby_rubocop.md
  docs/descriptors/salesforce.md
  docs/descriptors/salesforce_lightning_flow_scanner.md
  docs/descriptors/salesforce_sfdx_scanner_apex.md
  docs/descriptors/salesforce_sfdx_scanner_aura.md
  docs/descriptors/salesforce_sfdx_scanner_lwc.md
  docs/descriptors/snakemake_snakemake.md
  docs/used-by-stats.md
Labels: dependencies, automerge
